version: "3.8"

services:
  app:
    container_name: "tasks_api"
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://mysql_db:3306/task?allowPublicKeyRetrieval=true&useSSL=false
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=12345678
    depends_on:
      mysql_db:
        condition: service_healthy

  mysql_db:
    container_name: "mysql_db"
    image: "mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_DATABASE: "task"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p12345678"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  mysql-data:
